### ISSUE TITLE
ffmpeg: error while loading shared libraries: libnppig.so.11

### ISSUE THREAD

**Issue by wixahmed** [mdhiggins/sickbeard_mp4_automator#1478]
after running ffmpeg inside container i'm getting this error below , after the update , it was all working fine before the update can you please help 

root@/# ffmpeg
ffmpeg: error while loading shared libraries: libnppig.so.11: cannot open shared object file: No such file or directory

any solution to this please

i'm getting this error , inside container , when i'm trying run ffmpeg command inside container , after building the sonarr with DEVELOP TAG , can you please help , how to resolve / fix this issue please

**Comment by mdhiggins** [comment]
Are you building FFMPEG as well? This looks like a missing library

**Comment by wixahmed** [comment]
i'm building , i've got GPU , and hence im building using the develop tag and 4.4-nvidia tag

**Comment by wixahmed** [comment]
Issue is only happening in sonarr however radarr is working perfectly fine , using latest tag with same 4.4-nvidia on radarr

ARG ffmpeg_tag=4.4-nvidia
ARG sonarr_tag=develop
FROM jrottenberg/ffmpeg:${ffmpeg_tag} as ffmpeg
FROM linuxserver/sonarr:${sonarr_tag}
LABEL maintainer="mdhiggins <mdhiggins23@gmail.com>"

# Add files from ffmpeg
COPY --from=ffmpeg /usr/local/ /usr/local/

ENV SMA_PATH /usr/local/sma
ENV SMA_RS Sonarr
ENV SMA_UPDATE true

**Comment by mdhiggins** [comment]
I updated radarr and sonarr's build tag to include some additional dependencies, see if that helps

**Comment by wixahmed** [comment]
HI ,
no luck , it's still same , giving me same error 

ffmpeg: error while loading shared libraries: libnppig.so.11: cannot open shared object file: No such file or directory

**Comment by mdhiggins** [comment]
If you open up the container can you see if the following packages are installed?

libnppig10
libnppicc10
libnppidei10

(apt-get install)

**Comment by KaHooli** [comment]
I found with using build branch and jrottenberg/ffmpeg:4.4-nvidia2004, I had to use Radarr develop tag as it is based on Ubuntu 20.04 but latest tag is based on 18.04, and I had to add these dependancies after the ffmpeg is copied...
```dockerfile
# Add files from ffmpeg
COPY --from=ffmpeg /usr/local/ /usr/local/
# and its dependancies
RUN apt update && apt upgrade -y && apt install -y \
      libnppig10 \
      libnppicc10 \
      libnppidei10
```
Here is my docker compose entry that works using NVIDIA GPU transcoding...
```yaml
  # Radarr - Movie management
  radarr:
    # image: mdhiggins/radarr-sma:build
    # image: ghcr.io/mdhiggins/radarr-sma:build # doesn't exist yet
    image: kahooli/radarr-sma:build
    container_name: radarr
    restart: unless-stopped
    networks:
      t2_proxy:
        ipv4_address: 192.168.90.164
    depends_on:
      - prowlarr
      - nzbget
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu, compute, utility, graphics, video, display]
            driver: nvidia
    security_opt:
      - no-new-privileges:true
    # ports:
    #  - "$RADARR_PORT:7878"
    volumes:
      - $DOCKERDIR/appdata/radarr:/config
      # Optional. See why MediaCover is mounted as volume https://github.com/htpcBeginner/docker-traefik/discussions/147
      - $CONFIGDIR/radarr/MediaCover:/config/MediaCover
      - $PUBLICDIR/Downloads:/data/downloads
      - $PUBLICDIR/Videos:/data/videos
      - $DOCKERDIR/shared:/shared
      - "/etc/localtime:/etc/localtime:ro"
      - $DOCKERDIR/appdata/radarr-sma:/usr/local/sma/config
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      SMA_UPDATE: "true"
      SMA_CONFIG: /shared/sma/radarr-autoProcess.ini
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    build:
      # context: https://github.com/mdhiggins/radarr-sma.git#build
      context: https://github.com/KaHooli/radarr-sma.git#build
      args:
        - ffmpeg_tag=4.4-nvidia2004
        - radarr_tag=develop
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr-rtr-bypass.entrypoints=https"
      - "traefik.http.routers.radarr-rtr-bypass.rule=Host(`radarr.$DOMAINNAME0`) && (Headers(`X-Api-Key`, `$RADARR_API_KEY`) || Host(`radarr.$DOMAINNAME0`) && Query(`apikey`, `$RADARR_API_KEY`))"
      - "traefik.http.routers.radarr-rtr-bypass.priority=100"
      - "traefik.http.routers.radarr-rtr.entrypoints=https"
      - "traefik.http.routers.radarr-rtr.rule=Host(`radarr.$DOMAINNAME0`)"
      - "traefik.http.routers.radarr-rtr.priority=99"
      - "traefik.http.routers.radarr-rtr-bypass.middlewares=chain-no-auth@file"
      - "traefik.http.routers.radarr-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.radarr-rtr.service=radarr-svc"
      - "traefik.http.routers.radarr-rtr-bypass.service=radarr-svc"
      - "traefik.http.services.radarr-svc.loadbalancer.server.port=7878"
```
I worked with mdhiggins and jrottenberg via GitHub issue submissions awhile ago, and eventually got it to work at https://github.com/KaHooli/radarr-sma/tree/build , just haven't worked with them both to get properly resolved.

Also, mdhiggins was able to give me some assistance with getting the right settings in the autoProcess.ini file for NVIDIA GPU transcoding, see https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1444 .

I hope that gives some insight and help moving this issue to resolution.
