### ISSUE TITLE
radarr-sma autoProcess.ini is directory

### ISSUE THREAD

**Issue by kimo818** [mdhiggins/sickbeard_mp4_automator#983]
@mdhiggins 
This is for docker radarr-sma. I am unable to create the autoProcess.ini file.

I must be doing something very simple wrong, but  I cannot update the autoProcess.ini file because it is a directory. Please advise, I can't figure it out for the life of me. Thank you in advanced!

My yaml file is similar to what you suggest:
```
  radarr:
    image: mdhiggins/radarr-sma
    container_name: radarr
    volumes:
      - /opt/appdata/radarr:/config
      - /opt/appdata/sma/autoProcess.ini:/usr/local/bin/sma/sickbeard_mp4_automator/autoProcess.ini
      - /mnt/storage/movies:/movies
      - /mnt/storage/downloads:/downloads
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    restart:
      always
```
